/*=========================================================================

   Program: ParaView
   Module:    pqPOFFReaderPanel.h

   Copyright (c) 2005-2010 Sandia Corporation, Kitware Inc.
   All rights reserved.

   ParaView is a free software; you can redistribute it and/or modify it
   under the terms of the ParaView license version 1.2.

   See License_v1.2.txt for the full ParaView license.
   A copy of this license can be obtained by contacting
   Kitware Inc.
   28 Corporate Drive
   Clifton Park, NY 12065
   USA

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=========================================================================*/
// This class was developed by Takuya Oshima at Niigata University,
// Japan (oshima@eng.niigata-u.ac.jp).
// OPENFOAM(R) is a registered trade mark of OpenCFD Limited, the
// producer of the OpenFOAM software and owner of the OPENFOAM(R) and
// OpenCFD(R) trade marks. This code is not approved or endorsed by
// OpenCFD Limited.

#ifndef _pqPOFFDevReaderPanel_h
#define _pqPOFFDevReaderPanel_h

#include "pqAutoGeneratedObjectPanel.h"

// avoid possible name crash with the potentially builtin panel
#define pqPOFFReaderPanel pqPOFFDevReaderPanel

class pqDataRepresentation;
class pqPipelineSource;
class pqView;

class
#if !defined(POFFDevReaderPanelPlugin_EXPORTS)
PQCOMPONENTS_EXPORT
#endif
pqPOFFReaderPanel : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT
public:
  pqPOFFReaderPanel(pqProxy *, QWidget *);

  ~pqPOFFReaderPanel();

protected slots:
  void onFileNameModified();
  void onEditingFinished();
  void onWatchToggled(bool);
  void onRefresh();
  void onTimerTimeout();
  void onModifiedStateChanged();
  void onShowRegionNamesModified();
  void onDataUpdated();
  void onVisibilityChanged(pqPipelineSource *, pqDataRepresentation *);
  void onSourceDestroying(pqPipelineSource *);

private:
  void rescalePipelineSource(pqPipelineSource *);
  void rescaleAndRender();
  void removeAllRegionNameActors();
  void addRegionNameActors(pqView *);
  void removeRegionNameActors(pqView *);
  void deleteRegionNameActors();

  class pqImplementation;
  pqImplementation *Implementation;
};

#endif
